version: 43.0.9
pageUuid: 4de7985c-00b3-11ee-bb01-678b0c735990
appTemplate:
  queryStatusVisibility: false
  rootScreen: null
  version: 2.115.7
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
