id: productGroupSummaryTable
type: widget
subtype: TableWidget
template:
  ordered:
    - showCustomButton: false
    - sortMappedValue:
        ordered: []
    - _filteredSortedRenderedDataWithTypes: null
    - heightType: auto
    - normalizedData: null
    - rowHeight: dense
    - saveChangesDisabled: ''
    - columnTypeProperties:
        ordered:
          - ITEM_GROUP_DESC_EDITED:
              ordered: []
          - DVD_RELEASE_DT:
              ordered:
                - dateFormat: MM/dd/yyyy
          - BDD_RELEASE_DT:
              ordered:
                - dateFormat: MM/dd/yyyy
          - UHD_RELEASE_DT:
              ordered:
                - dateFormat: MM/dd/yyyy
          - CNT_SKUS:
              ordered:
                - showSeparators: true
                - padDecimal: true
          - ITEM_GROUP_ID:
              ordered: []
    - columnWidths:
        - object:
            id: ITEM_GROUP_ID
            value: 88.328125
        - object:
            id: DVD_RELEASE_DT
            value: 127.59375
        - object:
            id: BDD_RELEASE_DT
            value: 142.25
        - object:
            id: UHD_RELEASE_DT
            value: 145.25
        - object:
            id: ITEM_GROUP_DESC_EDITED
            value: 833.328125
    - showSummaryFooter: false
    - disableRowSelectInteraction: false
    - columnWidthsMobile: []
    - hasNextAfterCursor: ''
    - columnTypeSpecificExtras:
        ordered: []
    - onRowAdded: ''
    - columnHeaderNames:
        ordered:
          - MATERIAL_SEQ: SKUs
          - DVD_RELEASE_DT: DVD Release Date
          - EDIT_REQUIRED_IND: "\tStatus"
          - ITEM_GROUP_DESC_EDITED: Group Name
          - CNT_SKUS: SKU Count
          - BDD_RELEASE_DT: BDD Release Date
          - UHD_RELEASE_DT: UHD Release Date
          - ITEM_GROUP_ID: Group Id
    - alwaysShowPaginator: false
    - columnColors:
        ordered:
          - ITEM_GROUP_ID: ''
          - ITEM_GROUP_DESC_EDITED: ''
          - DVD_RELEASE_DT: ''
          - BDD_RELEASE_DT: ''
          - UHD_RELEASE_DT: ''
          - CNT_SKUS: ''
    - columnFrozenAlignments:
        ordered: []
    - allowMultiRowSelect: false
    - columnFormats:
        ordered:
          - ITEM_GROUP_DESC_EDITED: TextMultiDataCell
          - DVD_RELEASE_DT: DateDataCell
          - BDD_RELEASE_DT: DateDataCell
          - UHD_RELEASE_DT: DateDataCell
          - CNT_SKUS: NumberDataCell
          - ITEM_GROUP_ID: TextDataCell
    - columnRestrictedEditing:
        ordered: []
    - showFilterButton: true
    - _columnVisibility:
        ordered:
          - ITEM_GROUP_ID: true
          - MATERIAL_SEQ: true
    - _columnSummaryTypes:
        ordered:
          - ITEM_GROUP_DESC_EDITED: ''
          - DVD_RELEASE_DT: ''
          - BDD_RELEASE_DT: ''
          - UHD_RELEASE_DT: ''
          - CNT_SKUS: sum
          - ITEM_GROUP_ID: ''
    - _columnsWithLegacyBackgroundColor:
        set: []
    - showAddRowButton: false
    - _unfilteredSelectedIndex: null
    - nextBeforeCursor: ''
    - columnVisibility:
        ordered: []
    - selectedPageIndex: '0'
    - applyDynamicSettingsToColumnOrder: true
    - rowColor:
        array: []
    - actionButtonColumnName: Actions
    - resetAfterSave: true
    - filterStackType: and
    - hidden: ''
    - downloadRawData: true
    - showFetchingIndicator: true
    - serverPaginated: false
    - data: '{{ get_product_groups_default.data }}'
    - displayedData: null
    - actionButtons: []
    - actionButtonSelectsRow: true
    - selectRowByDefault: true
    - defaultSortByColumn: ''
    - paginationOffset: 0
    - columnAlignment:
        ordered:
          - ITEM_GROUP_DESC_EDITED: left
          - DVD_RELEASE_DT: center
          - BDD_RELEASE_DT: center
          - UHD_RELEASE_DT: center
          - CNT_SKUS: center
          - ITEM_GROUP_ID: center
    - columnSummaries:
        object: {}
    - showBoxShadow: false
    - sortedDesc: false
    - customButtonName: Custom Button
    - columnMappersRenderAsHTML:
        ordered: []
    - showRefreshButton: true
    - pageSize: '20'
    - useDynamicColumnSettings: true
    - actionButtonPosition: left
    - dynamicRowHeights: false
    - bulkUpdateAction: ''
    - afterCursor: ''
    - onCustomButtonPressQueryName: ''
    - changeSet:
        object: {}
    - sortedColumn: ''
    - _columnSummaryValues:
        ordered:
          - ITEM_GROUP_DESC_EDITED: ''
          - DVD_RELEASE_DT: ''
          - BDD_RELEASE_DT: ''
          - UHD_RELEASE_DT: ''
          - CNT_SKUS: ''
          - ITEM_GROUP_ID: ''
    - checkboxRowSelect: true
    - _compatibilityMode: false
    - showColumnBorders: false
    - clearSelectionLabel: Clear selection
    - _renderedDataWithTypes: null
    - columnAllowOverflow:
        ordered: []
    - beforeCursor: ''
    - serverPaginationType: limitOffsetBased
    - onRowSelect: ''
    - showDownloadButton: true
    - selectedIndex: null
    - defaultSortDescending: false
    - _sortedDisplayedDataIndices: null
    - dynamicColumnSettings: null
    - events:
        - ordered:
            - event: rowClick
            - type: widget
            - method: open
            - pluginId: editProductGroupModal
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: rowClick
            - type: widget
            - method: setValue
            - pluginId: selectProductGroup
            - targetId: null
            - params:
                ordered:
                  - value: >-
                      {{productGroupSummaryTable.selectedRow.data.ITEM_GROUP_ID}}
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: rowClick
            - type: widget
            - method: setValue
            - pluginId: selectProductGroupAssign
            - targetId: null
            - params:
                ordered:
                  - value: >-
                      {{productGroupSummaryTable.selectedRow.data.ITEM_GROUP_ID}}
            - waitType: debounce
            - waitMs: '0'
    - totalRowCount: ''
    - recordUpdates:
        array: []
    - newRow: null
    - emptyMessage: No rows found
    - columnEditable:
        ordered:
          - ITEM_GROUP_DESC_EDITED: false
    - _viewerColumnSummaryTypes:
        object: {}
    - filters:
        array: []
    - displayedDataIndices: null
    - disableSorting:
        ordered: []
    - columnMappers:
        ordered: []
    - showClearSelection: false
    - doubleClickToEdit: true
    - overflowType: pagination
    - _reverseSortedDisplayedDataIndices: null
    - showTableBorder: true
    - selectedCell:
        object:
          index: null
          data: null
          columnName: null
    - columns: []
    - defaultSelectedRow: none
    - freezeActionButtonColumns: false
    - sort: null
    - _columns:
        - ITEM_GROUP_ID
        - ITEM_GROUP_DESC_EDITED
        - DVD_RELEASE_DT
        - BDD_RELEASE_DT
        - UHD_RELEASE_DT
        - CNT_SKUS
    - sortByRawValue:
        ordered:
          - MATERIAL_SEQ: false
    - calculatedColumns: []
    - selectedRow:
        object:
          index: null
          data: null
    - showPaginationOnTop: false
    - _reverseDisplayedDataIndices: null
    - nextAfterCursor: ''
    - useCompactMode: false
style:
  ordered: []
position2:
  position2:
    container: tabbedContainer1
    subcontainer: 305c0
    row: 1.6
    height: 2
    width: 12
mobilePosition2:
  position2:
    container: tabbedContainer1
    subcontainer: 305c0
    row: 1.2
    height: 8
    width: 12
createdAt: 2023-03-17T22:04:06.882Z
