version: 43.0.9
pageUuid: 4ea5f466-1f56-11ee-b0b9-734d8a647254
appTemplate:
  appMaxWidth: 1560px
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  version: 3.28.3
  experimentalDataTabEnabled: true
