id: prodCompaniesRemoveTagsListbox
uuid: 7da9d7e2-f6fe-48d1-afd8-f3ac621fd8da
type: widget
subtype: MultiselectListboxWidget
template:
  ordered:
    - imageByIndex:
        array: []
    - _disabledByIndex: []
    - showActions: false
    - showSelectionIndicator: true
    - _values: []
    - iconByIndex:
        array: []
    - values:
        array: []
    - _iconByIndex: []
    - selectedIndexes:
        array: []
    - selectedItems:
        array: []
    - marginType: normal
    - hidden: false
    - customValidation: ''
    - data: '{{prodCompanyTagsVariable.value}}'
    - maxCount: null
    - searchMode: fuzzy
    - hideValidationMessage: false
    - fallbackTextByIndex:
        array: []
    - _fallbackTextByIndex: []
    - validationMessage: ''
    - automaticItemColors: false
    - itemAdornmentShape: circle
    - showInEditor: false
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: ''
    - hiddenByIndex:
        array: []
    - labelCaption: ''
    - labelWidth: '33'
    - deprecatedLabels:
        array: []
    - _hiddenByIndex: []
    - _captionByIndex: []
    - itemAdornmentSize: auto
    - searchTerm: ''
    - label: '           Select tags to keep'
    - _hasMigratedNestedItems: true
    - captionByIndex:
        array: []
    - _validate: false
    - itemMode: dynamic
    - labelWidthUnit: '%'
    - invalid: false
    - _tooltipByIndex: []
    - _colorByIndex: []
    - tooltipByIndex:
        array: []
    - colorByIndex:
        array: []
    - events: []
    - _ids: []
    - emptyMessage: No options
    - selectedLabels:
        array: []
    - disabled: false
    - labelPosition: top
    - minCount: null
    - _labels: []
    - labelWrap: false
    - disabledValues:
        array: []
    - disabledByIndex:
        array: []
    - maintainSpaceWhenHidden: false
    - _imageByIndex: []
    - required: false
    - labels:
        array: []
style:
  ordered: []
position2:
  position2:
    container: prodCompaniesTagsModal
    row: 1
    col: 1
    height: 4
    width: 11
createdAt: 2023-10-05T15:04:39.263Z
