id: productionStatusTableAddRowModalID
uuid: bf70796e-b93f-45c9-aafb-8fd7c827089a
type: widget
subtype: TextInputWidget2
template:
  ordered:
    - spellCheck: false
    - readOnly: false
    - iconAfter: ''
    - showCharacterCount: false
    - autoComplete: false
    - marginType: normal
    - maxLength: null
    - hidden: false
    - customValidation: ''
    - patternType: ''
    - hideValidationMessage: false
    - textBefore: ''
    - validationMessage: ''
    - textAfter: ''
    - showInEditor: false
    - showClear: false
    - pattern: ''
    - tooltipText: ''
    - labelAlign: left
    - formDataKey: '{{ self.id }}'
    - value: ''
    - labelCaption: ''
    - labelWidth: '33'
    - autoFill: ''
    - placeholder: Enter value
    - label: ID
    - _validate: false
    - labelWidthUnit: '%'
    - invalid: false
    - iconBefore: ''
    - minLength: null
    - inputTooltip: ''
    - events:
        ordered: []
    - autoCapitalize: none
    - loading: false
    - disabled: false
    - labelPosition: left
    - labelWrap: false
    - maintainSpaceWhenHidden: false
    - required: false
style:
  ordered: []
position2:
  position2:
    container: productionStatusTableAddRowModal
    row: 2
    height: 1
    width: 12
createdAt: 2023-11-08T22:28:40.928Z
