id: productionStatusTableAddRowModalText
uuid: 8c6a3640-68b2-4120-8b96-e54aaa1d8579
type: widget
subtype: TextWidget2
template:
  ordered:
    - heightType: auto
    - horizontalAlign: center
    - marginType: normal
    - hidden: false
    - imageWidth: fit
    - showInEditor: false
    - verticalAlign: center
    - tooltipText: ''
    - value: '**Add New Production Status**'
    - disableMarkdown: false
    - overflowType: scroll
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: productionStatusTableAddRowModal
    col: 2
    height: 0.6
    width: 9
createdAt: 2023-11-08T22:28:40.801Z
