id: prodCompaniesRemoveTagsButton
uuid: b86240ec-6187-47ba-9a48-80631afe07f9
type: widget
subtype: ButtonWidget2
template:
  ordered:
    - horizontalAlign: stretch
    - clickable: false
    - iconAfter: ''
    - submitTargetId: null
    - marginType: normal
    - hidden: false
    - text: Submit
    - showInEditor: false
    - tooltipText: ''
    - styleVariant: solid
    - submit: false
    - iconBefore: ''
    - events:
        - ordered:
            - event: click
            - type: state
            - method: setValue
            - pluginId: prodCompanyTagsVariable
            - targetId: null
            - params:
                ordered:
                  - value: '{{prodCompaniesRemoveTagsListbox.value}}'
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: click
            - type: widget
            - method: close
            - pluginId: prodCompaniesTagsModal
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - loading: false
    - loaderPosition: auto
    - disabled: false
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: prodCompaniesTagsModal
    row: 5.6
    col: 3
    height: 1
    width: 6
createdAt: 2023-10-05T15:06:34.392Z
