id: productionStatusTable
uuid: 7f9ce101-3a2b-4ccb-8962-b2e54ea644b7
type: widget
subtype: TableWidget2
template:
  ordered:
    - selectedRowKey: null
    - _nextAfterCursor: ''
    - _columnBackgroundColor:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _defaultSort: null
    - _clearChangesetOnSave: true
    - heightType: fixed
    - disableEdits: false
    - _rowHeight: small
    - _columnIds:
        - ac4c5
        - ff160
    - _isSaving: false
    - _actionIds: []
    - _clearChangeset: false
    - caseSensitiveFiltering: false
    - _limitOffsetRowCount: null
    - selectedSourceRow: null
    - _dynamicColumnsEnabled: false
    - disableSave: '{{securityGroupCheck.value}}'
    - _columnEditableOptions:
        ordered:
          - ac4c5:
              ordered: []
          - ff160:
              ordered: []
    - _toolbarPosition: bottom
    - _groupByColumns: []
    - _toolbarButtonLabel:
        ordered:
          - 1a: Filter
          - 3c: Download
          - 4d: Refresh
          - d057b: Add
    - _nextBeforeCursor: ''
    - _persistRowSelection: false
    - _toolbarButtonIcon:
        ordered:
          - 1a: bold/interface-text-formatting-filter-2
          - 3c: bold/interface-download-button-2
          - 4d: bold/interface-arrows-round-left
          - d057b: bold/interface-add-1
    - changesetArray:
        array: []
    - _toolbarButtonType:
        ordered:
          - 1a: filter
          - 3c: custom
          - 4d: custom
          - d057b: custom
    - _columnOptionList:
        ordered:
          - ac4c5:
              ordered: []
          - ff160:
              ordered: []
    - _columnValueOverride:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - marginType: normal
    - _showBorder: true
    - _templatePageSize: null
    - _dynamicColumnProperties:
        ordered: []
    - _showHeader: true
    - _currentPage: 0
    - _columnKey:
        ordered:
          - ac4c5: ID
          - ff160: NAME
    - hidden: false
    - _toolbarButtonIds:
        - 1a
        - 3c
        - 4d
        - d057b
    - data: '{{ get_ctm_production_status.data }}'
    - _cellSelection: none
    - _serverPaginated: false
    - _linkedFilterId: null
    - searchMode: fuzzy
    - _columnCellTooltip:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _columnFormat:
        ordered:
          - ac4c5: string
          - ff160: string
    - _cursorCache:
        object: {}
    - _calculatedPageSize: null
    - _primaryKeyColumnId: ac4c5
    - selectedDataIndex: null
    - _columnAlignment:
        ordered:
          - ac4c5: left
          - ff160: left
    - _actionIcon:
        ordered: []
    - _columnTooltip:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _columnIcon:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _columnCellTooltipMode:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _pageSize: null
    - showInEditor: false
    - selectedSourceRows:
        array: []
    - _enableExpandableRows: false
    - _selectMultipleRowsOnActionClick: 'no'
    - _columnSortDisabled:
        ordered:
          - ac4c5: false
          - ff160: false
    - undefined: null
    - _showSummaryRow: false
    - filterStack: null
    - _expandedRows: null
    - changesetObject: null
    - _actionDisabled:
        ordered: []
    - _columnReferenceId:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _dynamicColumnSource:
        array: []
    - _rowSelection: single
    - _columnCaption:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _dynamicColumnFormatOptions:
        ordered: []
    - _dynamicRowHeights: false
    - _columnFormatOptions:
        ordered:
          - ac4c5:
              ordered: []
          - ff160:
              ordered: []
    - _changeset: null
    - _afterCursor: ''
    - selectedRowKeys:
        array: []
    - _beforeCursor: ''
    - _columnSummaryAggregationMode:
        ordered:
          - ac4c5: none
          - ff160: none
    - searchTerm: ''
    - selectedRows:
        array: []
    - _disabledVirtualization: false
    - _expandedRowDataIndexes:
        array: []
    - _showColumnBorders: false
    - _columnStatusIndicatorOptions:
        ordered:
          - ac4c5:
              ordered: []
          - ff160:
              ordered: []
    - _columnSize:
        ordered:
          - ac4c5: 531.421875
          - ff160: 147.53125
    - _serverPaginationType: limitOffsetBased
    - _selectSingleRowsOnActionClick: replace
    - _showFooter: true
    - _groupedColumnConfig:
        ordered: []
    - _virtualizeStartIndex: 0
    - _toolbarButtonHidden:
        ordered:
          - 1a: ''
          - 3c: ''
          - 4d: ''
          - d057b: '{{securityGroupCheck.value}}'
    - _defaultFilters:
        ordered: []
    - events:
        - ordered:
            - event: clickToolbar
            - type: widget
            - method: open
            - pluginId: productionStatusTableAddRowModal
            - targetId: d057b
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - event: save
            - type: datasource
            - method: trigger
            - pluginId: update_ctm_production_status
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - type: widget
            - waitMs: '0'
            - waitType: debounce
            - event: clickToolbar
            - method: exportData
            - pluginId: productionStatusTable
            - targetId: 3c
        - ordered:
            - type: widget
            - waitMs: '0'
            - waitType: debounce
            - event: clickToolbar
            - method: refresh
            - pluginId: productionStatusTable
            - targetId: 4d
    - _columnEditable:
        ordered:
          - ac4c5: 'false'
          - ff160: true
    - _rowBackgroundColor:
        array: []
    - pagination: null
    - selectedDataIndexes:
        array: []
    - _columnGroupAggregationMode:
        ordered:
          - ac4c5: none
          - ff160: none
    - sortArray:
        array: []
    - _selectedCell: null
    - overflowType: scroll
    - selectedCell: null
    - _defaultSelectedRow:
        ordered:
          - mode: index
          - indexType: display
          - index: 0
    - _hasNextPage: false
    - _includeRowInChangesetArray: false
    - _columnPosition:
        ordered:
          - ac4c5: center
          - ff160: center
    - _enableSaveActions: true
    - _columnPlaceholder:
        ordered:
          - ac4c5: Enter value
          - ff160: Enter value
    - _defaultFilterOperator: and
    - _actionLabel:
        ordered: []
    - _virtualizeEndIndex: 0
    - selectedRow: null
    - _actionHidden:
        ordered: []
    - maintainSpaceWhenHidden: false
    - _columnHidden:
        ordered:
          - ac4c5: ''
          - ff160: ''
    - _columnLabel:
        ordered:
          - ac4c5: ID
          - ff160: Name
    - _showToolbar: true
style:
  ordered: []
position2:
  position2:
    container: referenceDataContainer
    subcontainer: c7966
    row: 1
    height: 7.2
    width: 12
createdAt: 2023-09-29T16:53:24.324Z
