id: productionStatusTableAddRowModalCancelButton
uuid: e7761bf3-7e78-4d24-a2b0-92f3745c023c
type: widget
subtype: ButtonWidget2
template:
  ordered:
    - horizontalAlign: stretch
    - clickable: false
    - iconAfter: ''
    - submitTargetId: null
    - marginType: normal
    - hidden: false
    - text: Cancel
    - showInEditor: false
    - tooltipText: ''
    - styleVariant: solid
    - submit: false
    - iconBefore: ''
    - events:
        - ordered:
            - event: click
            - type: widget
            - method: close
            - pluginId: productionStatusTableAddRowModal
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
    - loading: false
    - loaderPosition: auto
    - disabled: false
    - maintainSpaceWhenHidden: false
style:
  ordered: []
position2:
  position2:
    container: productionStatusTableAddRowModal
    row: 7.6
    col: 3
    height: 1
    width: 7
createdAt: 2023-11-08T22:28:41.319Z
