id: prodCompaniesTagsModal
uuid: 3edf0fab-d356-4952-b46e-1c81d7140e79
type: widget
subtype: ModalWidget
template:
  ordered:
    - opened: false
    - modalOverflowType: scroll
    - hidden: 'true'
    - onModalClose: ''
    - modalHeightType: fixed
    - tooltipText: ''
    - modalHeight: ''
    - onModalOpen: ''
    - events:
        - ordered:
            - event: open
            - type: script
            - method: run
            - pluginId: ''
            - targetId: null
            - params:
                ordered:
                  - src: >-
                      prodCompaniesRemoveTagsListbox.setValue(prodCompaniesRemoveTagsListbox.values);
            - waitType: debounce
            - waitMs: '0'
    - modalWidth: ''
    - closeOnOutsideClick: true
    - loading: ''
    - disabled: ''
    - buttonText: ''
style:
  ordered: []
position2:
  position2:
    container: tabbedContainer4
    subcontainer: f654f
    height: 1
    width: 1
createdAt: 2023-10-05T15:01:09.472Z
