id: userSettingsTable
uuid: 2d560937-3654-497b-ad65-55365bc9468e
type: widget
subtype: TableWidget2
template:
  ordered:
    - selectedRowKey: null
    - _nextAfterCursor: ''
    - _columnBackgroundColor:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _defaultSort: null
    - _clearChangesetOnSave: true
    - heightType: fixed
    - disableEdits: false
    - _rowHeight: small
    - _columnIds:
        - 22a72
        - f44dd
        - 7d0c8
        - 5d68a
        - f1073
    - _isSaving: false
    - _actionIds: []
    - _clearChangeset: false
    - caseSensitiveFiltering: false
    - _limitOffsetRowCount: null
    - selectedSourceRow: null
    - _dynamicColumnsEnabled: false
    - disableSave: false
    - _columnEditableOptions:
        ordered:
          - 5d68a:
              ordered: []
          - 22a72:
              ordered:
                - showStepper: true
          - f44dd:
              ordered:
                - showStepper: true
          - f1073:
              ordered: []
          - 7d0c8:
              ordered: []
    - _toolbarPosition: bottom
    - _groupByColumns: []
    - _toolbarButtonLabel:
        ordered:
          - 1a: Filter
          - 3c: Download
          - 4d: Refresh
    - _nextBeforeCursor: ''
    - _persistRowSelection: false
    - _toolbarButtonIcon:
        ordered:
          - 1a: bold/interface-text-formatting-filter-2
          - 3c: bold/interface-download-button-2
          - 4d: bold/interface-arrows-round-left
    - changesetArray:
        array: []
    - _toolbarButtonType:
        ordered:
          - 1a: filter
          - 3c: custom
          - 4d: custom
    - _columnOptionList:
        ordered:
          - 5d68a:
              ordered: []
          - 22a72:
              ordered: []
          - f44dd:
              ordered: []
          - f1073:
              ordered: []
          - 7d0c8:
              ordered: []
    - _columnValueOverride:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: '{{ _.startCase(item) }}'
    - marginType: normal
    - _showBorder: true
    - _templatePageSize: null
    - _dynamicColumnProperties:
        ordered: []
    - _showHeader: true
    - _currentPage: 0
    - _columnKey:
        ordered:
          - 5d68a: SETTING_VALUE
          - 22a72: SETTING_TYPE_ID
          - f44dd: USER_SETTING_ID
          - f1073: USER_ID
          - 7d0c8: SETTING_TYPE_NAME
    - hidden: false
    - _toolbarButtonIds:
        - 1a
        - 3c
        - 4d
    - data: '{{ get_user_preferences.data }}'
    - _cellSelection: none
    - _serverPaginated: false
    - _linkedFilterId: null
    - searchMode: fuzzy
    - _columnCellTooltip:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _columnFormat:
        ordered:
          - 5d68a: string
          - 22a72: decimal
          - f44dd: decimal
          - f1073: link
          - 7d0c8: string
    - _cursorCache:
        object: {}
    - _calculatedPageSize: null
    - _primaryKeyColumnId: f44dd
    - selectedDataIndex: null
    - _columnAlignment:
        ordered:
          - 5d68a: left
          - 22a72: center
          - f44dd: right
          - f1073: left
          - 7d0c8: left
    - _actionIcon:
        ordered: []
    - _columnTooltip:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _columnIcon:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _columnCellTooltipMode:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _pageSize: null
    - showInEditor: false
    - selectedSourceRows:
        array: []
    - _enableExpandableRows: false
    - _selectMultipleRowsOnActionClick: 'no'
    - _columnSortDisabled:
        ordered:
          - 5d68a: false
          - 22a72: false
          - f44dd: false
          - f1073: false
          - 7d0c8: false
    - _showSummaryRow: false
    - filterStack: null
    - _expandedRows: null
    - changesetObject: null
    - _actionDisabled:
        ordered: []
    - _columnReferenceId:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _dynamicColumnSource:
        array: []
    - _rowSelection: single
    - _columnCaption:
        ordered:
          - 5d68a: ''
          - 22a72: ''
          - f44dd: ''
          - f1073: ''
          - 7d0c8: ''
    - _dynamicColumnFormatOptions:
        ordered: []
    - _dynamicRowHeights: false
    - _columnFormatOptions:
        ordered:
          - 5d68a:
              ordered: []
          - 22a72:
              ordered:
                - showSeparators: true
                - notation: standard
          - f44dd:
              ordered:
                - showSeparators: true
                - notation: standard
          - f1073:
              ordered:
                - showUnderline: hover
          - 7d0c8:
              ordered: []
    - _changeset: null
    - _afterCursor: ''
    - selectedRowKeys:
        array: []
    - _beforeCursor: ''
    - _columnSummaryAggregationMode:
        ordered:
          - 5d68a: none
          - 22a72: none
          - f44dd: none
          - f1073: none
          - 7d0c8: none
    - searchTerm: ''
    - selectedRows:
        array: []
    - _disabledVirtualization: false
    - _expandedRowDataIndexes:
        array: []
    - _showColumnBorders: false
    - _columnStatusIndicatorOptions:
        ordered:
          - 5d68a:
              ordered: []
          - 22a72:
              ordered: []
          - f44dd:
              ordered: []
          - f1073:
              ordered: []
          - 7d0c8:
              ordered: []
    - _columnSize:
        ordered:
          - 22a72: 169.703125
          - f44dd: 100.6875
          - 7d0c8: 426.765625
          - 5d68a: 59.453125
          - f1073: 213.359375
    - _serverPaginationType: limitOffsetBased
    - _selectSingleRowsOnActionClick: replace
    - _showFooter: true
    - _groupedColumnConfig:
        ordered: []
    - _virtualizeStartIndex: 0
    - _toolbarButtonHidden:
        ordered:
          - 1a: ''
          - 3c: ''
          - 4d: ''
    - _defaultFilters:
        ordered: []
    - events:
        - ordered:
            - event: save
            - type: datasource
            - method: trigger
            - pluginId: update_user_preferences
            - targetId: null
            - params:
                ordered: []
            - waitType: debounce
            - waitMs: '0'
        - ordered:
            - type: widget
            - waitMs: '0'
            - waitType: debounce
            - event: clickToolbar
            - method: exportData
            - pluginId: userSettingsTable
            - targetId: 3c
        - ordered:
            - type: widget
            - waitMs: '0'
            - waitType: debounce
            - event: clickToolbar
            - method: refresh
            - pluginId: userSettingsTable
            - targetId: 4d
        - ordered:
            - event: clickCell
            - type: util
            - method: openUrl
            - pluginId: ''
            - targetId: f1073
            - params:
                ordered:
                  - url: mailto:{{ item }}
            - waitType: debounce
            - waitMs: '0'
    - _columnEditable:
        ordered:
          - 5d68a: 'true'
          - 22a72: 'false'
          - f44dd: false
          - f1073: ''
          - 7d0c8: ''
    - _rowBackgroundColor:
        array: []
    - pagination: null
    - selectedDataIndexes:
        array: []
    - _columnGroupAggregationMode:
        ordered:
          - 5d68a: none
          - 22a72: sum
          - f44dd: sum
          - f1073: none
          - 7d0c8: none
    - sortArray:
        array: []
    - _selectedCell: null
    - overflowType: scroll
    - selectedCell: null
    - _defaultSelectedRow:
        ordered:
          - mode: index
          - indexType: display
          - index: 0
    - _hasNextPage: false
    - _includeRowInChangesetArray: false
    - _columnPosition:
        ordered:
          - 5d68a: center
          - 22a72: center
          - f44dd: center
          - f1073: center
          - 7d0c8: center
    - _enableSaveActions: true
    - _columnPlaceholder:
        ordered:
          - 5d68a: ''
          - 22a72: Enter value
          - f44dd: Enter value
          - f1073: ''
          - 7d0c8: Enter value
    - _defaultFilterOperator: and
    - _actionLabel:
        ordered: []
    - _virtualizeEndIndex: 0
    - selectedRow: null
    - _actionHidden:
        ordered: []
    - maintainSpaceWhenHidden: false
    - _columnHidden:
        ordered:
          - 5d68a: ''
          - 22a72: 'false'
          - f44dd: 'true'
          - f1073: 'true'
          - 7d0c8: ''
    - _columnLabel:
        ordered:
          - 5d68a: Value
          - 22a72: ID
          - f44dd: User setting id
          - f1073: User id
          - 7d0c8: Name
    - _showToolbar: true
style:
  ordered: []
position2:
  position2:
    container: mainContainer
    subcontainer: 65d3e
    height: 8
    width: 12
createdAt: 2023-11-01T22:21:17.677Z
