version: 43.0.9
pageUuid: b6d4e0d0-055f-11ee-bb66-f3c28f4df722
appTemplate:
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  version: 3.2.2
  experimentalDataTabEnabled: true
